### ISSUE TITLE
Configuration should accept "verify_ssl"

### ISSUE THREAD

**Issue by yhernandez01** [DataDog/datadog-api-client-python#318]
The Configuration does not accept optional "verify_ssl" parameter, it sets to True automatically.

**Comment by ashemedai** [comment]
Related to this, but all code examples on the site will currently fail due to `AttributeError: type object 'Configuration' has no attribute 'verify_ssl'` since [rest.py](https://github.com/DataDog/datadog-api-client-python/blob/master/src/datadog_api_client/v2/rest.py#L53) explicitly tests against it: `if configuration.verify_ssl:`

**Comment by stenius** [comment]
@yhernandez01 you can do this
`configuration.verify_ssl = False`

**Comment by therve** [comment]
Hi,

There is a simple workaround, and I'm not sure why you would want skipping SSL verification against datadog servers anyway. Thanks.
